# Generated by Django 3.1.6 on 2021-02-10 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='enunciado de la pregunta')),
                ('image', models.ImageField(blank=True, upload_to='questions/%Y/%m/%d/', verbose_name='imagen del enunciado')),
                ('score', models.IntegerField(default=1, verbose_name='puntaje de pregunta')),
                ('is_example', models.BooleanField(default=False, verbose_name='pregunta de ejemplo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='fecha de edición')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
            },
        ),
        migrations.CreateModel(
            name='QuestionOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=500, verbose_name='texto de la opción')),
                ('image', models.ImageField(blank=True, upload_to='questions_options/%Y/%m/%d/', verbose_name='imagen de la opción')),
                ('is_correct', models.BooleanField(default=False, verbose_name='es correcta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='fecha de edición')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questions.question', verbose_name='pregunta')),
            ],
            options={
                'verbose_name': 'Opcion de pregunta',
                'verbose_name_plural': 'Opciones de pregunta',
            },
        ),
    ]
